spring:
  application:
    name: Menagerment
  config:
    location: classpath:/configOutput.yml
# profiles:
#    active: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://192.168.1.200:3306/jsunicom?useUnicode=true&characterEncoding=utf8"
    username: flowplatform
    password: 940430Dex
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 30000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    remove-abandoned: false
    remove-abandoned-timeout: 600
    log-abandoned: false
#  redis:
#    host: 192.168.1.200
#    port: 6379
#    password: 940430Dex
  #配置时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    #设置时区
    time-zone: GMT+8
  cloud:
    config:
      uri: http://config-server:8762
    
server:
  port: 8082
  context-path: /Managerment
#设置session
  session:
    timeout: 3600
  
management:
  security:
    enabled: false
    
mybatis:
  #加载指定路径下的文件
  mapper-locations: classpath:mapper/*.xml
  #设置别名
  type-aliases-package: com.shziyuan.flow.global.domain

security:
  oauth2:
    client:
      accessTokenUri: http://oauth2-server:8763/oauth/token
#      accessTokenUri: http://localhost:8763/oauth/token
      clientId: ldap
      clientSecret: 940430
      client-authentication-scheme: header
      authentication-scheme: header
      scope: web
      authorized-grant-types: password
    resource:
      user-info-uri: http://oauth2-server:8763/me
#      user-info-uri: http://localhost:8763/me
    sso:
      filter-order: 3
      
logging:
  #日志文件输出的位置
  path: /tmp/Menagerment
  #path: E:/readexcelTemp
  level:
    "com.ziyuan.web.manager": debug
  
#feign超时设置
ribbon.ReadTimeout: 60000
ribbon.ConnectTimeout: 60000

eureka:
 client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  

