FROM frolvlad/alpine-oraclejdk8
VOLUME /tmp
ADD notification-service-1.0.0.jar app.jar
#ADD application.yml application.yml
#RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java" ,"-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
EXPOSE 8764

