spring:
  rabbitmq:
    host: 192.168.1.200
    port: 5672
    username: mq
    password: 940430Dex
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        default-requeue-rejected: false