spring:
  datasource:
    url: "jdbc:mysql://support.shziyuan.cn:53306/flowplatform?useUnicode=true&characterEncoding=utf8"
    username: flowplatform
    password: 940430Dex

logging:
  path: /tmp/db-notify


  