package com.shziyuan.flow.global.common;

/**
 * 状态代码枚举
 */
public enum StatusCodeEnum {

	PLATFORM_NOTENOUGH_DISTRIBUTOR_BANLANCE("PE01","渠道余额不足"),
	PLATFORM_NOMORE_SUPPLIER("PE02","无更多供应商"),
	PLATFORM_RETRY("PE03","重试运营商提交"),
	PLATFORM_SUPPLIER_INTERFACE_ERROR("PE04","运营商接口报错"),
	PLATFORM_GETCONFIG_EXCEPTION("PE05","获取订单配置错误"),
	PLATFORM_SUPPLIER_REPORT_MODE_FAILD("PE06","供应商状态报告模式错误"),
	PLATFORM_SUPPLIER_REPORT_GETCONFIG_EXCEPTION("PE07","R 获取队列配置错误"),
	PLATFORM_CACHE_ORDER("PC01","缓存订单"),
	PLATFORM_REPORTPUSH_FAIL_IN_CACHE("PC03","缓存订单推送失败"),
	PLATFORM_REPORTPUSH_FAIL_IN_REPORT("PC04","状态订单推送失败"),
	PLATFORM_REPORTPUSH_SUCCESS_IN_REPORT("PC05","状态订单推送成功"),
	PLATFORM_SUPPLIER_SUBMIT_RETRY("PC02","供应商提交重试"),
	PLATFORM_NEXT_SUPPLIERSORT("PB01","当前供应商提交失败"),
	PLATFORM_SUPPLIER_REPORT_HOLD("PB02","供应商状态处理中"),
	PLATFORM_SUPPLIER_REPORT_FAILD("PB03","供应商状态失败"),
	PLATFORM_SUPPLIER_REPORT_OK("PB04","供应商状态成功"),
	PLATFORM_SUPPLIER_ONSUBMIT("PB05","向供应商提交请求"),
	PLATFORM_SUPPLIER_REPORT_ONSUBMIT("PB06","向供应商提交状态报告请求"),
	PLATFORM_SUPPLIER_SUBMIT_OK("P100","供应商提交成功"),
	PLATFORM_SUPPLIER_SUBMIT_FAILD("PE08","供应商提交失败"),
		
	INTERFACE_SUCCESS("0000","受理成功"),
	INTERFACE_RESP_INVALID_SIGN("0001","签名无效"),
	INTERFACE_RESP_INVALID_SKU("0001","SKU无效"),
	INTERFACE_RESP_NULL_DISTRIBUTOR("0001","渠道代码或产品代码无效"),
	INTERFACE_RESP_NOTENOUGH_BANLANCE("0008","账户余额不足"),
	INTERFACE_RESP_PARAM_ERROR("0001","接口参数错误"),
	INTERFACE_RESP_NOORDER("0001","不存在此订单"),
	
	DISTRIBUTOR_RESULT_RESP_FAILD("IE01","渠道接收失败"),
	DISTRIBUTOR_REPORT_PUSH_ONSUBMIT("IB01","向渠道推送状态"),
	DISTRIBUTOR_REPORT_PUSH_SUCCESS("IB02","渠道推送状态成功"),
	DISTRIBUTOR_REPORT_PUSH_RETRY("IB03","重试渠道推送状态"),
	
	REPORT_SUCCESS("0007","订购成功"),
	REPORT_NOMORE_SUPPLIER("0008","订单支付失败"),
	REPORT_FAILD("0008","订单支付失败"),
	REPORT_INPROGRESS("0009","订单处理中");
	
	public String code;
	public String message;
	
	private StatusCodeEnum(String code,String message) {
		this.code = code;
		this.message = message;
	}
}
