FROM frolvlad/alpine-oraclejdk8
VOLUME /tmp
ADD @target_file@ app.jar
ADD Shanghai /etc/localtime 
RUN echo "Asia/Shanghai" > /etc/timezone
ENTRYPOINT ["java" ,"-Djava.security.egd=file:/dev/./urandomi -Duser.timezone=GMT+08","-jar","/app.jar","@java_cmd_param@"]
EXPOSE @port@