FROM frolvlad/alpine-oraclejdk8
VOLUME /tmp
ADD queue-report-push-1.0.0.jar app.jar
ADD Shanghai /etc/localtime 
RUN echo "Asia/Shanghai" > /etc/timezone
ENTRYPOINT ["java" ,"-Djava.security.egd=file:/dev/./urandomi -Duser.timezone=GMT+08","-jar","/app.jar","--spring.config.location=classpath:/common.yml,classpath:/rabbit.yml"]
EXPOSE 